### PR TITLE
add KML support

### PR DESCRIPTION
**Pull request by tbo47**
Not fully tested but it gives an idea of what I'm planning on doing.
Thoughts?

### CODE REVIEW

**Review by Zemledelec — COMMENTED** [review]
unitilty for kml reading is good.
Is KML suitable to be whole layer object? For instance
```
let myKml = og.layer.KML('./countries.kml');
planet.addLayer(myKml);
```

**Comment by tbo47** [comment]
> unitilty for kml reading is good.
> Is KML suitable to be whole layer object? For instance
> 
> ```
> let myKml = og.layer.KML('./countries.kml');
> planet.addLayer(myKml);
> ```

I like it but I want to be able load kml files from the upload button and from urls. So maybe more something like:

```
let myKml = og.layer.KML('nameOfMyVector', options);
await myKml.addKmlFromUrl('./countries.kml');
planet.addLayer(myKml);
```
You can have a look at what I just commited.
What do you think?

**Comment by tbo47** [comment]
@Zemledelec ready for review.

**Review by Zemledelec — CHANGES_REQUESTED** [review]
Good day, Sir!

I see `#extent` member, I'd recommend to change it with native `_extent`, but be careful. Take a look at `Vector` layer and `Layer` classes first, because they already have `_extent `variable, and also `_extentMerc `variable. Also there is a function `getExtent ` already exists in `Layer`. Could you make changes according to the existing information, please!
By the way, good job! In future will be needed optimization, but for small laters would be good enough!
P.S.
...I dont realy like #variable signature, if you don't mind could you make a suggestion why #varname definition is better than ordinary variable definitions inside constructor body? Cheers,
Mike!

**Comment by tbo47** [comment]
I changed `#extent` to `_extent`
I now use the `_extent` defined in `Layer`
I removed `getExtent()` which is already in `Layer`
I added annotations.

I like the `#` keyword as it is the new javascript way to indicate it's a private variable.
`_` is just a convention. It doesn't prevent from using the variable.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

**Review by Zemledelec — APPROVED** [review]
Super! I think we need rules for style code. I do approve KML! Thank @tbo47, could you show where do you use it? I think KML needs more customization for billboards and labels.

**Pull request merged**
