### PR TITLE
refactor to use the class syntax

### PR DESCRIPTION
**Pull request by tbo47**
Refactor to use the `class` syntax instead of a javascript variable with `prototype` syntax.

2 reasons:
1/ generate `@types`. It doesn't work with the `prototype` syntax.
2/ to be consistent with the rest of the code.

### CODE REVIEW

**Comment by pavletto** [comment]
I think it's not very good.  @Zemledelec previously mentioned that some classes are made on prototypes for the sake of performance. @tbo47, types for vectors, or some prototyped staff generating correctly with this commit?

**Comment by tbo47** [comment]
oh, ok, I didn't know about performance.

yes, with the `class` syntax, `Extent.d.ts` is generated correctly.

**Comment by pavletto** [comment]
Maybe type not generated because the class file is not named as a declaration? I mean: file named as Extent.js and it contain class LonLat? I can't test this case right now

**Comment by Zemledelec** [comment]
Hey @tbo47, did you make performance tests? You could use any js perf test  to compare prototype instancing vs class instancing performance , such as creating, method accesing etc,  If class instancing tests not worse than prototypes, then I will accept classes and we will refactor every class in the library:)

P.S. here it is
https://github.com/openglobus/openglobus/issues/328

**Comment by tbo47** [comment]
I tried this

```
import { Extent } from '../../src/og/Extent.js';
import { ExtentNew } from '../../src/og/ExtentNew.js';

const t0 = performance.now();
for (let i = 0; i < 1000000; i++) {
  const test = Extent.fromTile(1, 1, 1, 1, 1);
}
const t1 = performance.now();
console.log((t1 - t0) + " millisecondes.");

const t2 = performance.now();
for (let i = 0; i < 1000000; i++) {
  const test = ExtentNew.fromTile(1, 1, 1, 1, 1);
}
const t3 = performance.now();
console.log((t3 - t2) + " millisecondes.")
```
I don't see a clear difference. It's kind of the same.
Thoughts?

**Comment by tbo47** [comment]
test 31.5 ms vs 27.300000000745058 ms
test 31.099999997764826 ms vs 25.699999999254942 ms
test 29.199999999254942 ms vs 27 ms
test 29.100000001490116 ms vs 30.100000001490116 ms
test 34.899999998509884 ms vs 28.600000001490116 ms

on this short test (5 tests total) the new implementation tends to be slightly faster.
@pavletto @Zemledelec

**Comment by pavletto** [comment]
@tbo47, benchmarks of static methods it's not that what we mean. Try to **create** instance of classes with es6 notaiton and prototype notaition.

**Comment by tbo47** [comment]
> @tbo47, benchmarks of static methods it's not that what we mean. Try to **create** instance of classes with es6 notaiton and prototype notaition.

I choose this static method because it creates a instance of Extent. Here https://github.com/openglobus/openglobus/blob/master/src/og/Extent.js#L118

But I can create a test with more method calls if needed.

**Comment by tbo47** [comment]
this test tests 10 millions times:
1/ a static method
2/ instantiate a new Extent
3/ call a method/prototype

```
import { Extent } from '../../src/og/Extent.js';
import { ExtentNew } from '../../src/og/ExtentNew.js';

const nb = 10000000;
const t0 = performance.now();
for (let i = 0; i < nb; i++) {
  const test = Extent.fromTile(1, 1, 1, 1, 1);
  test.getCenter();
}
const t1 = performance.now();
const test1 = (t1 - t0) + " ms"

const t2 = performance.now();
for (let i = 0; i < nb; i++) {
  const test = ExtentNew.fromTile(1, 1, 1, 1, 1);
  test.getCenter();
}
const t3 = performance.now();
const test2 = (t3 - t2) + " ms"
console.log("test " + test1 + " vs " + test2)
```

on Google Chrome 93, it gives us:
```
test 217.60000000149012 ms vs 213 ms
test 227.39999999850988 ms vs 234.90000000223517 ms
test 226.80000000074506 ms vs 219 ms
test 225.10000000149012 ms vs 218.89999999850988 ms
test 228.89999999850988 ms vs 229 ms
test 227.29999999701977 ms vs 221.40000000223517 ms
test 225.89999999850988 ms vs 215.70000000298023 ms
```

**Comment by Zemledelec** [comment]
Yep! I've made tests too! And it looks true!
https://jsbench.me/9dktu8sjza/1

**Review by Zemledelec — APPROVED** [review]

**Review by Zemledelec — APPROVED** [review]

**Pull request merged**
