### PR TITLE
KML Rendering Improvements

### PR DESCRIPTION
**Pull request by ghost**
Improved KML rendering by parsing some KML Style tags.

### CODE REVIEW

**Comment by Zemledelec** [comment]
Hi! Please add common pull request 
INSERT A SMALL DESCRIPTION OF WHAT YOU CHANGED HERE
and verify that...
 npm test passes
 npm run api passes
 npm run lint passes
 npm run build still works

**Comment by tbo47** [comment]
I'm not sure I understand why to change from XML to JSON. It seems over complicated.

**Comment by Zemledelec** [comment]
> I'm not sure I understand why to change from XML to JSON. It seems over complicated.

Sorry, I didnt get it, where is kml is changed to json?

**Comment by tbo47** [comment]
the `_xml2json(...)` method

**Comment by ghost** [comment]
> I'm not sure I understand why to change from XML to JSON. It seems over complicated.

Yes, it is overly complicated... I'd been working a lot in Web Workers where you don't have DOMparser() so I kind of just did it automatically.

I can rewrite this code.

**Comment by ghost** [comment]
I removed _xml2json().

* npm test passes
* npm run api passes
* npm run lint fails and I haven't figured out what's wrong...
* npm run build passes

**Comment by tbo47** [comment]
What about something like https://github.com/openglobus/openglobus/pull/511/files

The idea is to get the `Placemark` tags. In each of them I extract the `coordinates`, `color` and `width` tags with this code:
```javascript
const coordinatesRaw = Array.from(placemark.getElementsByTagName("coordinates")).at(0)
```

**Comment by ghost** [comment]
I'm not certain that code would easily adapt to eventually supporting multiple styles (e.g. for <MultiGeometry>)?

For example, if you have an <IconStyle> and then a <LineStyle> "extractFirst()" would only get the color from the <IconStyle> tag?

**Comment by tbo47** [comment]
> I'm not certain that code would easily adapt to eventually supporting multiple styles (e.g. for )?
> 
> For example, if you have an and then a "extractFirst()" would only get the color from the tag?

Can you give an kml example of what you are describing?

Something like this?
```xml
<Document>
	<Style id="yellowLineGreenPoly000">
		<LineStyle>
			<color>7f0000ff</color>
			<width>4</width>
		</LineStyle>
		<PolyStyle>
			<color>7f00ff00</color>
		</PolyStyle>
	</Style>
       ...
	<Placemark>
		<styleUrl>#yellowLineGreenPoly000</styleUrl>
		<LineString>
			<coordinates>
                        ...
```

**Comment by ghost** [comment]
That's a much harder case to parse right now.  For this initial parsing, I was thinking of Style tags inside the Placemark.  Take a look at [this random file I found here](https://gist.github.com/ismail44/880dfedaed05186f14ff).

**Comment by tbo47** [comment]
> That's a much harder case to parse right now. For this initial parsing, I was thinking of Style tags inside the Placemark. Take a look at [this random file I found here](https://gist.github.com/ismail44/880dfedaed05186f14ff).

oh ok. So `LineStyle` styles the `Point` and `PolyStyle` styles `Polygon`? It's pretty common, I see that in the kml files I'm working with.

```xml
  <Placemark>
    <Style>
      <LineStyle>
        <color>ff000000</color>
      </LineStyle>
      <PolyStyle>
        <color>7f9f7fe0</color>
      </PolyStyle>
    </Style>
    <MultiGeometry>
      <Point>
        <coordinates>138.600000,-34.910000</coordinates>
      </Point>
      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>
            138.64,-34.93 138.64,-34.94 138.63,-34.94 138.62,-34.94
            ...
  ```

**Comment by ghost** [comment]
I added parsing <heading> but when I rotate the map, the icon doesn't rotate with the map.  For example, an icon with a heading of 180 always points towards the bottom of the screen.

Is there any way to make a Billboard rotate when the map rotates?

**Comment by Zemledelec** [comment]
> I added parsing but when I rotate the map, the icon doesn't rotate with the map. For example, an icon with a heading of 180 always points towards the bottom of the screen.
> 
> Is there any way to make a Billboard rotate when the map rotates?

...property rotation in screen coordinates only.

Something like this:
`entity.billboard.setRotation(45 * Math.PI / 180.0)`

for this was alignedAxis, but i cant say it does work now...

**Pull request merged**
