### PR TITLE
New profile for zh_cn

### PR DESCRIPTION
**Pull request by wewindy**
I add a new `README_CN.md` for Chinese Description for this lib, and also add some demo code to `README.md`.

To adapt to the native ES modules on nowadays browsers, I added the option of esm to the rollup configuration and turned on the creation of sourcemap for debugging.

In order to make the written code format uniform, I added `prettier`, `husky` and other configurations to automatically format the code whenever precommit.

### CODE REVIEW

**Review by Zemledelec — COMMENTED** [review]
Good request! Thank you!

1) Is it possible to prevent commits if they don't follow prettier rules, instead of doing commits directly?

2) Why do you use **npx lint-staged** when you use lint-staged in the package.json

3) Frankly speaking, I'm not familiar with prettier, but it looks promising. 
I'd like to see something
```
        var xmin = bounds[0], xmax = bounds[3],
              ymin = bounds[1], ymax = bounds[4],
              zmin = bounds[2], zmax = bounds[5];
```
 instead of prettier do in this case. 

Also I'd like this 
```
         this.handler.addPrograms([
            toneMapping()
        ]);
```
instead of   ` this.handler.addPrograms([toneMapping()]);`

Also better not touch call functions like this:
`let samples = gl.getInternalformatParameter(gl.RENDERBUFFER, gl[internalFormat], gl.SAMPLES);`

Sometimes, it's better to see the call function in one line, but prettier makes it in multiple lines.

Also, I'd like not change the code like this:
` if (name === "keypress" || name === "charkeypress" || name === "keyfree") {`

  Could you change the rules in prettier?
  
P.S. 
I don't know prettier rules

**Comment by wewindy** [comment]
Tks!

1. It seems to be no way, unless you don't use husky to handle precommit. 
But I think it is no worry. If the codes does not meet the existed rules, prettier will format the code before git commit. 

If the codes match no rules:

``` js
var xmin = bounds[0], xmax = bounds[3],
    ymin = bounds[1], ymax = bounds[4],
    zmin = bounds[2], zmax = bounds[5];
```

, the code remains as it is. Prettier is a subjective tool. In this pull request, there are not many rules I set, I just set some basic style formatting rules, which will be explained below.

2. The dependency `lint-staged` is used to filter files. The "\*.{js,ts}" rule means that only the modified js & ts files are formatted using prettier. If you like, you can change it to "\*.{js,ts,css}" to support formatting css files.

3. The entire formatting process is roughly as follows:

- run `git commit -m "Your description."` 
- → `husky` catch precommit hook 
- → then, will run `npx lint-staged` 
- → `lint-staged` uses the rules in package.json to filter files and executes the `prettier --write` command
- → finally, git commit

4. After setting a proper `printWidth` value, for example, I set 100 in `.prettierrc.js`, then when the characters of each line of code over than 100 characters, prettier will format the code.
That is to say, cut off the long line into multi. 
If the original code, such as a function call, is multi-line style:

``` js
this.handler.addPrograms([    // 26 chars
    toneMapping()    //  13 chars
]);   //  3 chars
```

, and the number of characters in each line does not exceed the set `printWidth` value, then prettier will not format the code.

5. If the condition expression is so long:

``` js
if (name === "keypress" || name === "charkeypress" || name === "keyfree" || name === "aaaaaaaaaaa" || name === "bbbbbb") {  // 120 chars
```

The prettier will be split into multiple lines. After all, some times, a line more than 100 characters is really long, most of the time you need to scroll the screen to see the whole. 

6. Briefly explain the prettier configuration I submitted:

``` js
module.exports = {
    printWidth: 100, // Up to 100 characters per line
    tabWidth: 4, // Use 4 characters for indentation
    useTabs: false, // Do not use `\t` characters for indentation, but use spaces
    semi: true, // Need to end with a semicolon
    singleQuote: false, // Use double quotes for string and object keys (when needed)
    quoteProps: "as-needed", // Use quote for the keys of objects when necessary, such as "content-type"
    trailingComma: "none", // The last expression does not need to end with a comma
    bracketSpacing: true, // Spaces are required for the head and tail inside the braces
    arrowParens: "always", // When the arrow function has only one parameter, the parameter need to wrap with parentheses
    
    // 0 to Infinity, means that the entire content of the file is processed by the prettier 
    rangeStart: 0,
    rangeEnd: Infinity,
    
    requirePragma: false, // No need to write @prettier at the beginning of the file
    insertPragma: false, // Don't automatically insert the `@prettier` character at the beginning of the file
    
    // These 2 rules seem to be of little help to this project, I forgot to delete them
    proseWrap: "preserve",
    htmlWhitespaceSensitivity: "css",
    
    endOfLine: "auto" // The setting of line breaks. `auto` means to use crlf on Windows and lf on other operating systems
};
```

**Comment by Zemledelec** [comment]
No luck with the follows, prettier always makes it changed:

```
this.handler.addPrograms([
    toneMapping()
]);

```
```
var xmin = bounds[0], xmax = bounds[3],
    ymin = bounds[1], ymax = bounds[4],
    zmin = bounds[2], zmax = bounds[5];
```

Could you fix the prettier rules for such code styles?

**You can try it in bv/Box.js**

**Review by Zemledelec — APPROVED** [review]

**Comment by wewindy** [comment]
> No luck with the follows, prettier always makes it changed:
> 
> ```
> this.handler.addPrograms([
>     toneMapping()
> ]);
> ```
> 
> ```
> var xmin = bounds[0], xmax = bounds[3],
>     ymin = bounds[1], ymax = bounds[4],
>     zmin = bounds[2], zmax = bounds[5];
> ```
> 
> Could you fix the prettier rules for such code styles?
> 
> **You can try it in bv/Box.js**

ok, I will have a try later

**Comment by Zemledelec** [comment]
> > No luck with the follows, prettier always makes it changed:
> > ```
> > this.handler.addPrograms([
> >     toneMapping()
> > ]);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > var xmin = bounds[0], xmax = bounds[3],
> >     ymin = bounds[1], ymax = bounds[4],
> >     zmin = bounds[2], zmax = bounds[5];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you fix the prettier rules for such code styles?
> > **You can try it in bv/Box.js**
> 
> ok, I will have a try later

Hi, onsummer! How is it going with pretifier?

**Comment by wewindy** [comment]
> > > No luck with the follows, prettier always makes it changed:
> > > ```
> > > this.handler.addPrograms([
> > >     toneMapping()
> > > ]);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > var xmin = bounds[0], xmax = bounds[3],
> > >     ymin = bounds[1], ymax = bounds[4],
> > >     zmin = bounds[2], zmax = bounds[5];
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Could you fix the prettier rules for such code styles?
> > > **You can try it in bv/Box.js**
> > 
> > 
> > ok, I will have a try later
> 
> Hi, onsummer! How is it going with pretifier?

I am so sorry for the delay in reply msg, cuz recently work is too busy. 
I tried, but it seems no rules for keep the code mentioned above unchange.

However, I found if you add a special comment, `// prettier-ignore`, above the code statement that you don't want to be formatted by prettier, it will not be formatted. eg:

``` js
/* bv/Box.js */

// prettier-ignore
var xmin = bounds[0], xmax = bounds[3],
    ymin = bounds[1], ymax = bounds[4],
    zmin = bounds[2], zmax = bounds[5];
```

Little trouble, don’t know if it’s acceptable?

**Comment by Zemledelec** [comment]
Thanks @onsummer! Glad to see any progress. Sure, it will help people to contribute proper(other word common) code style!

**Comment by wewindy** [comment]
> Thanks @onsummer! Glad to see any progress. Sure, it will help people to contribute proper(other word common) code style!

I will continue to contribute and study this lib.
Happy to be a contributor ~

**Pull request merged**
